#!/bin/bash

do_start()
{
echo "Starting celery...."
su -l ec2-user -c "cd /opt/app/gladminds; nohup bin/celery -A gladminds worker --loglevel info -f tasks.out &" > /dev/null 2>&1
su -l ec2-user -c "cd /opt/app/gladminds; nohup bin/celery -A gladminds beat --loglevel info -f beat.out &" > /dev/null 2>&1
}

do_stop()
{
ps -ef | grep celery | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
}

case $1 in
start) do_start $2
;;
stop) do_stop
;;
esac
