##################################################
# file: brand_client.py
# 
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     /usr/bin/wsdl2py -b brand.wsdl
# 
##################################################

from brand_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
from ZSI.schema import GED, GTD
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class brandLocator:
    brandSOAP_address = "http://localhost:8000/"
    def getbrandSOAPAddress(self):
        return brandLocator.brandSOAP_address
    def getbrandSOAP(self, url=None, **kw):
        return brandSOAPSOAP(url or brandLocator.brandSOAP_address, **kw)

# Methods
class brandSOAPSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: getBrand
    def getBrand(self, request, **kw):
        if isinstance(request, GetBrandInput) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://localhost:8000/productPurchase/GetBrand", **kw)
        # no output wsaction
        response = self.binding.Receive(GetBrandOutput.typecode)
        return response

GetBrandInput = GED("urn:ZSI", "brandInput").pyclass

GetBrandOutput = GED("urn:ZSI", "brandOutput").pyclass
