##################################################
# file: brand_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b brand.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from brand_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
GetBrandInput = GED("http://www.example.org/brand/", "brandInput").pyclass

GetBrandOutput = GED("http://www.example.org/brand/", "brandOutput").pyclass


# Service Skeletons
class brand(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getBrand(self, ps, **kw):
        request = ps.Parse(GetBrandInput.typecode)
        return request,GetBrandOutput()

    soapAction['http://www.example.org/productPurchase/GetBrand'] = 'soap_getBrand'
    root[(GetBrandInput.typecode.nspname,GetBrandInput.typecode.pname)] = 'soap_getBrand'

