##################################################
# file: couponRedeem_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b couponRedeem.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from couponRedeem_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
GetCouponRedeemInput = GED("urn:ZSI", "CouponRedeemInput").pyclass

GetCouponRedeemOutput = GED("urn:ZSI", "CouponRedeemOutput").pyclass


# Service Skeletons
class couponRedeem(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getCouponRedeem(self, ps, **kw):
        request = ps.Parse(GetCouponRedeemInput.typecode)
        return request,GetCouponRedeemOutput()

    soapAction['http://localhost:8000/productPurchase/GetCouponRedeem'] = 'soap_getCouponRedeem'
    root[(GetCouponRedeemInput.typecode.nspname,GetCouponRedeemInput.typecode.pname)] = 'soap_getCouponRedeem'

