##################################################
# file: couponRedeem_types.py
#
# schema types generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#    /usr/bin/wsdl2py -b couponRedeem.wsdl
#
##################################################

import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED
from ZSI.generate.pyclass import pyclass_type

##############################
# targetNamespace
# urn:ZSI
##############################

class ns0:
    targetNamespace = "urn:ZSI"

    class couponRedeemInput_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "couponRedeemInput"
        schema = "urn:ZSI"
        def __init__(self, **kw):
            ns = ns0.couponRedeemInput_Dec.schema
            TClist = [ZSI.TC.String(pname="CHASSIS", aname="_CHASSIS", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname="SER_ADV_MOBILE", aname="_SER_ADV_MOBILE", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TCtimes.gDateTime(pname="CLOSED_DATE", aname="_CLOSED_DATE", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TCtimes.gDateTime(pname="ACTUAL_SERVICE_DATE", aname="_ACTUAL_SERVICE_DATE", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TCnumbers.Ilong(pname="ACTUAL_KMS", aname="_ACTUAL_KMS", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname="UCN_NO", aname="_UCN_NO", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:ZSI","couponRedeemInput")
            kw["aname"] = "_couponRedeemInput"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                __metaclass__ = pyclass_type
                typecode = self
                def __init__(self):
                    # pyclass
                    self._CHASSIS = None
                    self._SER_ADV_MOBILE = None
                    self._CLOSED_DATE = None
                    self._ACTUAL_SERVICE_DATE = None
                    self._ACTUAL_KMS = None
                    self._UCN_NO = None
                    return
            Holder.__name__ = "couponRedeemInput_Holder"
            self.pyclass = Holder

    class couponRedeemOutput_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "couponRedeemOutput"
        schema = "urn:ZSI"
        def __init__(self, **kw):
            ns = ns0.couponRedeemOutput_Dec.schema
            TClist = [ZSI.TC.String(pname="RESPONSE_CODE", aname="_RESPONSE_CODE", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:ZSI","couponRedeemOutput")
            kw["aname"] = "_couponRedeemOutput"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                __metaclass__ = pyclass_type
                typecode = self
                def __init__(self):
                    # pyclass
                    self._RESPONSE_CODE = None
                    return
            Holder.__name__ = "couponRedeemOutput_Holder"
            self.pyclass = Holder

# end class ns0 (tns: urn:ZSI)
