##################################################
# file: productPurchase_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b productPurchase.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from productPurchase_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
GetProductPurchaseInput = GED("urn:ZSI", "productPurchaseInput").pyclass

GetProductPurchaseOutput = GED("urn:ZSI", "productPurchaseOutput").pyclass


# Service Skeletons
class productPurchase(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getProductPurchase(self, ps, **kw):
        request = ps.Parse(GetProductPurchaseInput.typecode)
        return request,GetProductPurchaseOutput()

    soapAction['http://localhost:8000/productPurchase/GetProductPurchase'] = 'soap_getProductPurchase'
    root[(GetProductPurchaseInput.typecode.nspname,GetProductPurchaseInput.typecode.pname)] = 'soap_getProductPurchase'

