##################################################
# file: productDispatch_client.py
# 
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     /usr/bin/wsdl2py -b productDispatch.wsdl
# 
##################################################

from productDispatch_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
from ZSI.schema import GED, GTD
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class productDispatchLocator:
    productDispatchSOAP_address = "http://localhost:8000/"
    def getproductDispatchSOAPAddress(self):
        return productDispatchLocator.productDispatchSOAP_address
    def getproductDispatchSOAP(self, url=None, **kw):
        return productDispatchSOAPSOAP(url or productDispatchLocator.productDispatchSOAP_address, **kw)

# Methods
class productDispatchSOAPSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: getProductDispatch
    def getProductDispatch(self, request, **kw):
        if isinstance(request, GetProductDispatchInput) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://localhost:8000/productPurchase/GetProductDispatch", **kw)
        # no output wsaction
        response = self.binding.Receive(GetProductDispatchOutput.typecode)
        return response

GetProductDispatchInput = GED("urn:ZSI", "productDispatchInput").pyclass

GetProductDispatchOutput = GED("urn:ZSI", "productDispatchOutput").pyclass
