##################################################
# file: productDispatch_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b productDispatch.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from productDispatch_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
GetProductDispatchInput = GED("urn:ZSI", "productDispatchInput").pyclass

GetProductDispatchOutput = GED("urn:ZSI", "productDispatchOutput").pyclass


# Service Skeletons
class productDispatch(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getProductDispatch(self, ps, **kw):
        request = ps.Parse(GetProductDispatchInput.typecode)
        return request,GetProductDispatchOutput()

    soapAction['http://localhost:8000/productPurchase/GetProductDispatch'] = 'soap_getProductDispatch'
    root[(GetProductDispatchInput.typecode.nspname,GetProductDispatchInput.typecode.pname)] = 'soap_getProductDispatch'

