CUSTOMER_REGISTER = "Dear {0}, Congratulations. You have enrolled for AfterBuy; a completely \
hassle free one-stop place to value-track-care all your purchases & beyond."
SERVICE_DETAIL = "CUSTOMER ID: {0} PRODUCT ID: {1} COUPONS: {2}"
REGISTER_PRODUCT = "Successfully register PRODUCT ID: {0} INTO CUSTOMER ID: {1}"
INVALID_SERVICE_DETAIL = "Invalid CUSTOMER ID: {0}"
VALID_COUPON="COUPON :{0} is valid"
EXPIRED_COUPON="COUPON :{0} is no more valid now"
INVALID_COUPON_DETAIL="Wrong COUPON ID:{0}"
UNAUTHORISED_SA="DEALER NOT AUTHORISED:{0}"
REMINDER_COUPON_EXPIRY = "Reminder: Your Coupon {0} for product {1} will expire on {2}"