CUSTOMER_REGISTER = "CUSTOMER ID: {0} Welcome to gladminds"
SERVICE_DETAIL = "CUSTOMER ID: {0} PRODUCT ID: {1} SERVICE: {2}"
REGISTER_PRODUCT = "Successfully register PRODUCT ID: {0} INTO CUSTOMER ID: {1}"